mklink /J %appdata%\foobar2000-v2 foobar2000-v2 
mklink /J %appdata%\ExplorerPatcher ExplorerPatcher
mklink /J %appdata%\Rizonesoft Rizonesoft 
mklink /J %userprofile%\Documents\WindowsPowerShell ps5
mklink /J %userprofile%\Documents\PowerShell ps7
mklink /J %localappdata%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState terminal
mklink /J %userprofile%\portable\KeyOp\data keyop
mklink /J %appdata%\nvda nvda
mklink /H %appdata%\Notepad2.ini unsorted\Notepad2.ini 